package com.floxy.viewer.render

import com.floxy.viewer.model.FlowModel
import com.floxy.viewer.model.FlowStepType

class MermaidRenderer {
    fun render(model: FlowModel): String {
        val sb = StringBuilder()
        sb.appendLine("%% Auto-generated by Floxy Viewer")
        sb.appendLine("flowchart TD")
        sb.appendLine("%% Title: ${model.name} v${model.version}")

        // Declare nodes as boxes with labels
        model.steps.values.forEach { step ->
            val extras = buildString {
                if (step.type == FlowStepType.Join && step.joinStrategy != null) {
                    append("\\n[")
                    append(step.joinStrategy)
                    step.joinQuorum?.let { append(":$it") }
                    append("]")
                }
                if (!step.handler.isNullOrEmpty()) {
                    append("\\n(")
                    append(step.handler)
                    append(")")
                }
                // type marker
                append("\\n<")
                append(
                    when (step.type) {
                        FlowStepType.Task -> "task"
                        FlowStepType.Fork -> "fork"
                        FlowStepType.Join -> "join"
                        FlowStepType.SavePoint -> "savepoint"
                        FlowStepType.Condition -> "cond"
                        FlowStepType.Human -> "human"
                        FlowStepType.Parallel -> "parallel"
                    }
                )
                append(">")
            }

            val displayName = if (step.name.contains("_branch_")) step.name.substringBefore("_branch_") else step.name
            val id = alias(step.name)
            // Choose shape by type
            val nodeText = "$displayName$extras"
            val shaped = when (step.type) {
                FlowStepType.Task -> "[\"$nodeText\"]"            // rectangle
                FlowStepType.Fork -> "[[\"$nodeText\"]]"          // subroutine-like
                FlowStepType.Join -> "((\"$nodeText\"))"          // circle
                FlowStepType.SavePoint -> "([\"$nodeText\"])"     // stadium
                FlowStepType.Condition -> "{\"$nodeText\"}"       // diamond/decision
                FlowStepType.Human -> "(\"$nodeText\")"           // rounded
                FlowStepType.Parallel -> "[[\"$nodeText\"]]"      // same as Fork
            }
            sb.appendLine("$id$shaped")
            // Color by type using per-node style
            val fill = when (step.type) {
                FlowStepType.Task -> "#E3F2FD"
                FlowStepType.Fork -> "#FFF3E0"
                FlowStepType.Join -> "#E8F5E9"
                FlowStepType.SavePoint -> "#F3E5F5"
                FlowStepType.Condition -> "#FFFDE7"
                FlowStepType.Human -> "#FBE9E7"
                FlowStepType.Parallel -> "#ECEFF1"
            }
            sb.appendLine("style $id fill:$fill,stroke:#455A64,color:#000")
        }

        // Edges
        model.edges.forEach { e ->
            val label = when (e.kind) {
                "onFailure" -> "|onFailure|"
                "else" -> "|else|"
                "then" -> "|then|"
                "branch" -> "|branch|"
                "join" -> "|join|"
                "cond_true" -> "|true|"
                "cond_false" -> "|false|"
                "split" -> "|split|"
                else -> ""
            }
            val arrow = when (e.kind) {
                "onFailure", "cond_false", "else" -> "-.->"
                else -> "-->"
            }
            // Mermaid expects labels between the arrow and the target: A -->|label| B
            sb.appendLine("${alias(e.from)} $arrow$label ${alias(e.to)}")
        }

        return sb.toString()
    }

    private fun alias(name: String): String = name.replace("[^A-Za-z0-9_]".toRegex(), "_")
}