package com.floxy.viewer.render

import com.floxy.viewer.model.FlowModel
import com.floxy.viewer.model.FlowStepType

class MermaidRenderer {
    fun render(model: FlowModel): String {
        val sb = StringBuilder()
        sb.appendLine("%% Auto-generated by Floxy Viewer")
        sb.appendLine("flowchart TD")
        sb.appendLine("%% Title: ${model.name} v${model.version}")

        // Declare nodes as boxes with labels
        model.steps.values.forEach { step ->
            val extras = buildString {
                if (step.type == FlowStepType.Join && step.joinStrategy != null) {
                    append("\\n[")
                    append(step.joinStrategy)
                    step.joinQuorum?.let { append(":$it") }
                    append("]")
                }
                if (!step.handler.isNullOrEmpty()) {
                    append("\\n(")
                    append(step.handler)
                    append(")")
                }
                // type marker
                append("\\n<")
                append(
                    when (step.type) {
                        FlowStepType.Task -> "task"
                        FlowStepType.Fork -> "fork"
                        FlowStepType.Join -> "join"
                        FlowStepType.SavePoint -> "savepoint"
                        FlowStepType.Condition -> "cond"
                        FlowStepType.Human -> "human"
                        FlowStepType.Parallel -> "parallel"
                    }
                )
                append(">")
            }

            val displayName = if (step.name.contains("_branch_")) step.name.substringBefore("_branch_") else step.name
            sb.appendLine("${alias(step.name)}[\"$displayName$extras\"]")
        }

        // Edges
        model.edges.forEach { e ->
            val label = when (e.kind) {
                "onFailure" -> "|onFailure|"
                "else" -> "|else|"
                "then" -> "|then|"
                "branch" -> "|branch|"
                "join" -> "|join|"
                "cond_true" -> "|true|"
                "cond_false" -> "|false|"
                "split" -> "|split|"
                else -> ""
            }
            val arrow = when (e.kind) {
                "onFailure", "cond_false", "else" -> "-.->"
                else -> "--->"
            }
            sb.appendLine("${alias(e.from)} $arrow ${alias(e.to)} $label")
        }

        return sb.toString()
    }

    private fun alias(name: String): String = name.replace("[^A-Za-z0-9_]".toRegex(), "_")
}